security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /user
            logout:
                path: app_logout
                target: /
            custom_authenticator: App\Security\LoginAuthenticator


            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true


    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    access_control:

        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
       
 
        #- { path: ^/user/edit, roles: ROLE_USER }


        - { path: ^/articles$, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/articles/\d+$, roles: IS_AUTHENTICATED_ANONYMOUSLY } 

        # Les actions CRUD sont réservées aux administrateurs
        - { path: ^/articles/new, roles: ROLE_ADMIN }
        - { path: ^/articles/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/articles/\d+/delete, roles: ROLE_ADMIN }

        #Post et commentaires
        - {path: ^/poste/new, roles: ROLE_USER}
        - {path: ^/poste/\d+/edit, roles: ROLE_USER}
        - {path: ^/poste/\d+/delete, roles: ROLE_USER}
        - {path: ^/commentaire/new, roles: ROLE_USER}
        - {path: ^/commentaire/\d+/edit, roles: ROLE_USER}
        - {path: ^/commentaire/\d+/delete, roles: ROLE_USER}


        #Catégories
        - {path: ^/categories/show, roles: ROLE_USER}
        - {path: ^/categorie/index, roles: ROLE_ADMIN}
