security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email


    firewalls:
        dev:
            pattern: ^/(css|images|js)/
            security: false

        main:
            provider: app_user_provider
            entry_point: form_login  # Ajout du entry_point
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home
            logout:
                path: app_logout
                target: home
            custom_authenticator: App\Security\AppAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/edit, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }
        
        #Article
        - { path: ^/articles$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/articles/\d+$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/articles/new, roles: ROLE_ADMIN }
        - { path: ^/articles/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/articles/\d+/delete, roles: ROLE_ADMIN }


        #HomePage
        - { path: '^/$', roles: IS_AUTHENTICATED_ANONYMOUSLY}