controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET]

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

user_index:
    path: /user
    controller: App\Controller\UserController::index
    methods: [GET]

profile:
    path: /profile
    controller: App\Controller\HomeController::profile
    methods: [GET, POST]

user_new:
    path: /user/new
    controller: App\Controller\UserController::new
    methods: [GET, POST]

user_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

user_delete:
    path: /user/{id}/delete
    controller: App\Controller\UserController::delete
    methods: [POST]
    requirements:
        id: '\d+'

article_index:
    path: /articles
    controller: App\Controller\ArticleController::index
    methods: [GET]

article_new:
    path: /articles/new
    controller: App\Controller\ArticleController::new
    methods: [GET, POST]

article_edit:
    path: /articles/{id}/edit
    controller: App\Controller\ArticleController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

article_delete:
    path: /articles/{id}/delete
    controller: App\Controller\ArticleController::delete
    methods: [POST]
    requirements:
        id: '\d+'

poste_index:
    path: /poste
    controller: App\Controller\PosteController::index
    methods: [GET]

poste_new:
    path: /poste/new
    controller: App\Controller\PosteController::new
    methods: [GET, POST]

poste_show:
    path: /poste/{id}
    controller: App\Controller\PosteController::show
    methods: [GET]

poste_edit:
    path: /poste/{id}/edit
    controller: App\Controller\PosteController::edit
    methods: [GET, POST]

poste_delete:
    path: /poste/{id}/delete
    controller: App\Controller\PosteController::delete
    methods: [POST]

categorie_index:
    path: /categorie
    controller: App\Controller\CategorieController::index
    methods: [GET]

categorie_show:
    path: /categorie/{id}
    controller: App\Controller\CategorieController::show
    methods: [GET]