controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_index:
    path: /user
    controller: App\Controller\UserController::index
    methods: [GET]

user_new:
    path: /user/new
    controller: App\Controller\UserController::new
    methods: [GET, POST]

user_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

user_delete:
    path: /user/{id}/delete
    controller: App\Controller\UserController::delete
    methods: [POST]
    requirements:
        id: '\d+'
