controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


favicon:
    path: /favicon.ico
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirect
    defaults:
        path: /images/favicon.ico
        permanent: true

home:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET]


app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

user_index:
    path: /user
    controller: App\Controller\UserController::index
    methods: [GET]

user_new:
    path: /user/new
    controller: App\Controller\UserController::new
    methods: [GET, POST]

user_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

user_delete:
    path: /user/{id}/delete
    controller: App\Controller\UserController::delete
    methods: [POST]
    requirements:
        id: '\d+'

article_index:
    path: /articles
    controller: App\Controller\ArticleController::index
    methods: [GET]

article_new:
    path: /articles/new
    controller: App\Controller\ArticleController::new
    methods: [GET, POST]

article_edit:
    path: /articles/{id}/edit
    controller: App\Controller\ArticleController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

article_delete:
    path: /articles/{id}/delete
    controller: App\Controller\ArticleController::delete
    methods: [POST]
    requirements:
        id: '\d+'
